<?php

namespace Cmi\ApiBundle\Repository;

/**
 * AccidentTravailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentTravailRepository extends \Doctrine\ORM\EntityRepository
{
}
