<?php

namespace Cmi\ApiBundle\Repository;

/**
 * AgentMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentMaterielRepository extends \Doctrine\ORM\EntityRepository
{
}
