<?php

namespace Cmi\ApiBundle\Repository;

/**
 * DiagnostiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnostiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
