<?php

namespace Cmi\ApiBundle\Repository;

/**
 * Famille_medicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Famille_medicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
