<?php

namespace Cmi\ApiBundle\Repository;

/**
 * FamilleMedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleMedicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
