<?php

namespace Cmi\ApiBundle\Repository;

/**
 * FamillePathologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamillePathologieRepository extends \Doctrine\ORM\EntityRepository
{
}
