<?php

namespace Cmi\ApiBundle\Repository;

/**
 * Forme_medicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forme_medicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
