<?php

namespace Cmi\ApiBundle\Repository;

/**
 * FormeMedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormeMedicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
