<?php

namespace Cmi\ApiBundle\Repository;

/**
 * NatureLesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureLesionRepository extends \Doctrine\ORM\EntityRepository
{
}
