<?php

namespace Cmi\ApiBundle\Repository;

/**
 * NatureAccidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureAccidentRepository extends \Doctrine\ORM\EntityRepository
{
}
