<?php

namespace Cmi\ApiBundle\Repository;

/**
 * SiegeLesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiegeLesionRepository extends \Doctrine\ORM\EntityRepository
{
}
