<?php

namespace Cmi\ApiBundle\Repository;

/**
 * SoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoinsRepository extends \Doctrine\ORM\EntityRepository
{
}
