<?php

namespace Cmi\ApiBundle\Repository;

/**
 * TemoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemoinRepository extends \Doctrine\ORM\EntityRepository
{
}
