cmi_api_home:
    path:     /api
    defaults: { _controller: CmiApiBundle:Api:index }

carte:
    type:     rest
    resource: Cmi\ApiBundle\Controller\CarteController

# agent:
#     type:     rest
#     resource: Cmi\ApiBundle\Controller\AgentController

assurance:
    type:     rest
    resource: Cmi\ApiBundle\Controller\AssuranceController

# ayant_droit:
#     type:     rest
#     resource: Cmi\ApiBundle\Controller\Ayant_droitController

# autre:
#     type:     rest
#     resource: Cmi\ApiBundle\Controller\AutreController

categorie:
    type:     rest
    resource: Cmi\ApiBundle\Controller\CategorieController

entite:
    type:     rest
    resource: Cmi\ApiBundle\Controller\EntiteController

examen:
    type:     rest
    resource: Cmi\ApiBundle\Controller\ExamenController

lieu_travail:
    type:     rest
    resource: Cmi\ApiBundle\Controller\Lieu_travailController

praticien:
    type:     rest
    resource: Cmi\ApiBundle\Controller\PraticienController

proffession:
    type:     rest
    resource: Cmi\ApiBundle\Controller\ProfessionController

type_contrat:
    type:     rest
    resource: Cmi\ApiBundle\Controller\Type_contratController
    

patient:
    type:   rest
    resource: Cmi\ApiBundle\Controller\PatientController

cause:
    type:   rest
    resource: Cmi\ApiBundle\Controller\CauseController

diagnostique:
    type:   rest
    resource: Cmi\ApiBundle\Controller\DiagnostiqueController
    
etape:
    type:   rest
    resource: Cmi\ApiBundle\Controller\EtapeController
    
famille_medicament:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Famille_medicamentController
    
famille_pathologie:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Famille_pathologieController
    
forme_medicament:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Forme_medicamentController
    
medicament:
    type:   rest
    resource: Cmi\ApiBundle\Controller\MedicamentController
    
pathologie:
    type:   rest
    resource: Cmi\ApiBundle\Controller\PathologieController
    
ordonnance:
    type:   rest
    resource: Cmi\ApiBundle\Controller\OrdonnanceController
    
consultation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\ConsultationController
    
type_praticien:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Type_praticienController
    
societe:
    type:   rest
    resource: Cmi\ApiBundle\Controller\SocieteController
    
motif:
    type:   rest
    resource: Cmi\ApiBundle\Controller\MotifController
    
acte:
    type:   rest
    resource: Cmi\ApiBundle\Controller\ActeController
    
specialite:
    type:   rest
    resource: Cmi\ApiBundle\Controller\SpecialiteController
    
soins:
    type:   rest
    resource: Cmi\ApiBundle\Controller\SoinsController

resultat_examen:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Resultat_examenController

type_examen:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Type_examenController

type_patient:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Type_patientController

#Accident
equipe:
    type:   rest
    resource: Cmi\ApiBundle\Controller\EquipeController

nature_lesion:
    type:   rest
    resource: Cmi\ApiBundle\Controller\NatureLesionController

agent_materiel:
    type:   rest
    resource: Cmi\ApiBundle\Controller\SecteurController

secteur:
    type:   rest
    resource: Cmi\ApiBundle\Controller\AgentMaterielController

siegelesion:
    type:   rest
    resource: Cmi\ApiBundle\Controller\SiegeLesionController

cartificat_medical:
    type:   rest
    resource: Cmi\ApiBundle\Controller\CertificatMedicalController

nature_accident:
    type:   rest
    resource: Cmi\ApiBundle\Controller\NatureAccidentController


activite:
    type:   rest
    resource: Cmi\ApiBundle\Controller\ActiviteController

#Relation

carte_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\CarteRelationController

type_patient_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\Type_patientRelationController

proffession_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\ProfessionRelationController

lieu_travail_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\Lieu_travailRelationController


categorie_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\CategorieRelationController


type_contrat_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\Type_contratRelationController

entite_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\EntiteRelationController

# ayant_droit_relation:
#     type:   rest
#     resource: Cmi\ApiBundle\Controller\Relation\Ayant_droitRelationController

# type_examen_relation:
#     type:   rest
#     resource: Cmi\ApiBundle\Controller\Relation\Type_examenRelationController

resultat_examen_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\Resultat_examenRelationController

patient_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\PatientRelationController


soins_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\SoinsRelationController

motif_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\MotifRelationController


etape_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\EtapeRelationController

specialite_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\SpecialiteRelationController

praticien_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\PraticienRelationController

ordonnance_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\OrdonnanceRelationController

medicament_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\MedicamentRelationController

diagnostique_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\DiagnostiqueRelationController

famille_pathologie_relation:
    type:   rest
    resource: Cmi\ApiBundle\Controller\Relation\Famille_pathologieRelationController