services:
#    cmi_api.example:
#        class: Cmi\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.cors_listener:
      class:      Cmi\ApiBundle\Listener\CorsListener
      tags:
         - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }